name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
        - brockman
    steps:
    - uses: actions/checkout@v3
    - name: Install QEMU (ARM)
      run: sudo apt-get install -y qemu-user-static
      if: ${{ matrix.system == 'brockman' }}
    - name: Install Nix (ARM)
      uses: cachix/install-nix-action@v16
      if: ${{ matrix.system == 'brockman' }}
      with:
        extra_nix_config: |
          system = aarch64-linux
    - name: Install Nix (x86_64)
      uses: cachix/install-nix-action@v16
      if: ${{ matrix.system != 'brockman' }}
    - name: nixos-rebuild dry-build
      run: nix run nixpkgs#nixos-rebuild -- dry-build  --flake $GITHUB_WORKSPACE#${{matrix.system}}
